function recipeUser() {
  return [
    { user_name: "hiroshi", user_password: "scsk1" },
    { user_name: "emiko", user_password: "scsk2" },
    { user_name: "料理チャンネルAI", user_password: "scsk3" },
    { user_name: "ゆう", user_password: "scsk4" },
    { user_name: "ノリノリキッチン", user_password: "scsk5" },
    { user_name: "メゾンtokyo", user_password: "scsk6" },
    { user_name: "syunsuke", user_password: "scsk7" },
    { user_name: "makoto", user_password: "scsk8" },
    { user_name: "メグメグ", user_password: "scsk9" },
    { user_name: "takuyaaaa", user_password: "scsk10" },
    { user_name: "hanako", user_password: "scsk11" },
    { user_name: "ryo99", user_password: "scsk12" },
    { user_name: "しんちゃん", user_password: "scsk13" },
    { user_name: "junjun", user_password: "scsk14" },
    { user_name: "yuta", user_password: "scsk15" },
    { user_name: "mai", user_password: "scsk16" },
    { user_name: "satchan", user_password: "scsk17" },
    { user_name: "gaku", user_password: "scsk18" },
    { user_name: "tokyochef", user_password: "scsk19" },
    { user_name: "hayato", user_password: "scsk20" },
  ];
}

function recipeData() {
  return [
    {
      title: "黄金比のキーマカレー",
      description: "スパイスから作る本格派",
      ingredients: "ひき肉, 玉ねぎ, カレー粉",
      instructions: "炒めて煮るだけ",
      genre: "和食",
      servenumber: 2,
      user_id: 1,
      created_at: "2024-03-14 10:08:21",
      image_url: "/キーマカレー.jpeg",
    },
    {
      title: "濃厚カルボナーラ",
      description: "生クリーム不使用の本場風",
      ingredients: "パスタ, 卵, パンチェッタ",
      instructions: "茹でて和える",
      genre: "イタリアン",
      servenumber: 1,
      user_id: 2,
      created_at: "2024-06-23 23:54:32",
      image_url: "/carbo.jpg",
    },
    {
      title: "パラパラチャーハン",
      description: "強火が決め手の絶品中華",
      ingredients: "ご飯, 卵, ネギ",
      instructions: "一気に炒める",
      genre: "中華",
      servenumber: 1,
      user_id: 3,
      created_at: "2024-12-15 04:12:19",
      image_url: "/tyahan.jpg",
    },
    {
      title: "肉じゃが",
      description: "お袋の味、定番の煮物",
      ingredients: "牛肉, じゃがいも, 人参",
      instructions: "コトコト煮込む",
      genre: "和食",
      servenumber: 3,
      user_id: 4,
      created_at: "2025-02-01 11:32:47",
      image_url: "/nikujaga.avif",
    },
    {
      title: "ガパオライス",
      description: "ナンプラーが香るタイ料理",
      ingredients: "鶏ひき肉, バジル, 卵",
      instructions: "目玉焼きを添えて",
      genre: "洋食",
      servenumber: 1,
      user_id: 5,
      created_at: "2025-05-26 17:45:00",
      image_url: "/gapao.jpeg",
    },
    {
      title: "具沢山豚汁",
      description: "野菜をたっぷり摂取",
      ingredients: "豚肉, ごぼう, 大根",
      instructions: "味噌を溶き入れる",
      genre: "和食",
      servenumber: 4,
      user_id: 6,
      created_at: "2025-07-07 09:01:55",
      image_url: "/tonjiru.jpg",
    },
    {
      title: "ペペロンチーノ",
      description: "ニンニクと唐辛子のシンプルパスタ",
      ingredients: "パスタ, ニンニク, 唐辛子",
      instructions: "乳化がコツ",
      genre: "イタリアン",
      servenumber: 1,
      user_id: 7,
      created_at: "2025-09-16 13:25:13",
      image_url: "/pepe.jpeg",
    },
    {
      title: "麻婆豆腐",
      description: "ピリ辛が癖になる一品",
      ingredients: "豆腐, 挽肉, 豆板醤",
      instructions: "とろみをつける",
      genre: "中華",
      servenumber: 2,
      user_id: 8,
      created_at: "2025-10-22 02:18:43",
      image_url: "/mabo.jpg",
    },
    {
      title: "ハンバーグ",
      description: "ふっくらジューシーな仕上がり",
      ingredients: "合い挽き肉, パン粉, 玉ねぎ",
      instructions: "両面を焼いて蒸らす",
      genre: "洋食",
      servenumber: 2,
      user_id: 9,
      created_at: "2025-12-29 19:57:38",
      image_url: "/hambarg.avif",
    },
    {
      title: "シーザーサラダ",
      description: "自家製ドレッシングのサラダ",
      ingredients: "レタス, ベーコン, チーズ",
      instructions: "和えるだけ",
      genre: "洋食",
      servenumber: 2,
      user_id: 10,
      created_at: "2026-01-03 08:22:10",
      image_url: "/sizer.jpg",
    },
    {
      title: "サバの味噌煮",
      description: "ご飯が進む定番和食",
      ingredients: "サバ, 生姜, 味噌",
      instructions: "落とし蓋をして煮る",
      genre: "和食",
      servenumber: 2,
      user_id: 11,
      created_at: "2025-06-18 16:04:12",
      image_url: "/saba.avif",
    },
    {
      title: "エビチリ",
      description: "プリプリのエビをチリソースで",
      ingredients: "エビ, ケチャップ, 豆板醤",
      instructions: "素早く火を通す",
      genre: "中華",
      servenumber: 2,
      user_id: 12,
      created_at: "2024-09-02 07:11:29",
      image_url: "/ebi.avif",
    },
    {
      title: "マルゲリータピザ",
      description: "生地から作る手作りピザ",
      ingredients: "強力粉, トマト, モッツァレラ",
      instructions: "オーブンで焼く",
      genre: "イタリアン",
      servenumber: 2,
      user_id: 13,
      created_at: "2025-11-05 21:33:30",
      image_url: "/pizza.jpeg",
    },
    {
      title: "オムライス",
      description: "昔ながらの洋食屋さんの味",
      ingredients: "卵, ご飯, ケチャップ",
      instructions: "綺麗に包む",
      genre: "洋食",
      servenumber: 1,
      user_id: 14,
      created_at: "2024-08-30 18:39:59",
      image_url: "/オム.jpeg",
    },
    {
      title: "親子丼",
      description: "トロトロ卵の優しい味",
      ingredients: "鶏肉, 卵, 玉ねぎ",
      instructions: "短時間で仕上げる",
      genre: "和食",
      servenumber: 1,
      user_id: 15,
      created_at: "2024-11-05 15:41:50",
      image_url: "/don.webp",
    },
    {
      title: "餃子",
      description: "皮から手作りモチモチ餃子",
      ingredients: "豚肉, キャベツ, 餃子の皮",
      instructions: "焼き色をつける",
      genre: "中華",
      servenumber: 3,
      user_id: 16,
      created_at: "2024-04-08 22:04:41",
      image_url: "/gyoza.jpg",
    },
    {
      title: "パンケーキ",
      description: "ふわふわな朝食メニュー",
      ingredients: "小麦粉, 牛乳, 卵",
      instructions: "弱火で焼く",
      genre: "デザート",
      servenumber: 2,
      user_id: 17,
      created_at: "2026-01-27 05:54:37",
      image_url: "/cake.jpg",
    },
    {
      title: "照り焼きチキン",
      description: "甘辛いタレが絶妙",
      ingredients: "鶏もも肉, 醤油, みりん",
      instructions: "タレを煮詰める",
      genre: "和食",
      servenumber: 2,
      user_id: 18,
      created_at: "2025-04-23 12:06:28",
      image_url: "/teri.jpg",
    },
    {
      title: "クラムチャウダー",
      description: "あさりの旨味たっぷりスープ",
      ingredients: "あさり, 牛乳, ジャガイモ",
      instructions: "煮込む",
      genre: "洋食",
      servenumber: 3,
      user_id: 19,
      created_at: "2024-10-19 01:20:16",
      image_url: "/kura.webp",
    },
    {
      title: "ティラミス",
      description: "大人のデザート",
      ingredients: "マスカルポーネ, コーヒー",
      instructions: "冷やし固める",
      genre: "デザート",
      servenumber: 4,
      user_id: 20,
      created_at: "2026-02-01 17:40:22",
      image_url: "/ティラミス.jpeg",
    },
  ];
}

module.exports = {
  recipeUser,
  recipeData,
};
